# Generated by Django 6.0.5 on 2026-05-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_smscode_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ID сообщения у провайдера'),
        ),
    ]
