# Generated by Django 6.0.5 on 2026-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_smscode_provider_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(max_length=4, verbose_name='Код'),
        ),
    ]
