# Generated by Django 6.0.5 on 2026-05-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cargo_multitenancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_key',
            field=models.CharField(default=1, editable=False, max_length=64, unique=True, verbose_name='Ключ входа'),
            preserve_default=False,
        ),
    ]
