# Generated by Django 6.0.5 on 2026-06-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('users', '0007_user_is_cargo_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_codes', to='cargo.cargocompany', verbose_name='Карго-центр'),
        ),
    ]
