# Generated by Django 6.0.5 on 2026-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_smscode_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попыток ввода'),
        ),
    ]
