# Generated by Django 6.0.5 on 2026-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_smscode_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_china_staff',
            field=models.BooleanField(default=False, help_text='Принимает товары на складе в Китае: доступны только статусы китайского склада и отправки, без выдачи и управления.', verbose_name='Оператор склада в Китае'),
        ),
    ]
