# Generated by Django 6.0.5 on 2026-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_china_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_tabs',
            field=models.JSONField(blank=True, default=list, help_text='Список вкладок панели, доступных обычному оператору. Игнорируется для админов карго и супер-владельца.', verbose_name='Доступные вкладки'),
        ),
    ]
