# Generated by Django 6.0.5 on 2026-08-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_seed_operator_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], help_text='Каким каналом код реально ушёл. Пусто — доставка не удалась.', max_length=16, verbose_name='Канал доставки'),
        ),
    ]
