# Generated by Django 6.0.5 on 2026-08-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_smscode_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID сообщения у провайдера'),
        ),
    ]
