# Generated by Django 6.0.5 on 2026-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'ordering': ('title',), 'verbose_name': 'ПВЗ', 'verbose_name_plural': 'ПВЗ'},
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=255, verbose_name='График работы'),
        ),
    ]
