# Generated by Django 6.0.5 on 2026-09-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_points', '0004_alter_pickuppoint_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='client_code_prefix',
            field=models.CharField(blank=True, help_text='Свой префикс этого ПВЗ: «ISIM» → ISIM0001. Пусто — берётся префикс карго, и код будет общим на все ПВЗ. Уникален среди всех карго и ПВЗ: по коду клиента коробку опознают в Китае, где посылки лежат вместе. Менять можно в любой момент — выданные коды не пересчитываются.', max_length=10, verbose_name='Префикс кода клиента'),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='client_code_seq',
            field=models.PositiveIntegerField(default=0, help_text='Номер последнего кода, выданного этим ПВЗ. Своя нумерация включается вместе с префиксом.', verbose_name='Счётчик кодов клиентов'),
        ),
    ]
