# Generated by Django 6.0.5 on 2026-05-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_registered', 'Регистрация клиента'), ('user_login', 'Вход клиента'), ('user_logout', 'Выход клиента'), ('user_blocked', 'Блокировка клиента'), ('user_unblocked', 'Разблокировка клиента'), ('parcel_imported', 'Импорт посылки'), ('parcel_status_changed', 'Смена статуса посылки'), ('parcel_issued', 'Выдача посылки'), ('city_delivery_created', 'Создана доставка по городу'), ('city_delivery_delivered', 'Завершена доставка по городу'), ('pinduoduo_connected', 'Подключение Pinduoduo'), ('pinduoduo_disconnected', 'Отключение Pinduoduo'), ('pinduoduo_synced', 'Синхронизация Pinduoduo'), ('admin_action', 'Действие администратора')], max_length=64, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_targeted', to=settings.AUTH_USER_MODEL, verbose_name='Кого касается')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='common_audi_action_f07e2b_idx'), models.Index(fields=['target_user', 'created_at'], name='common_audi_target__a2305a_idx')],
            },
        ),
    ]
