# Generated by Django 6.0.5 on 2026-07-29 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, help_text='Базовое имя получателя. К нему добавляется код клиента.', max_length=128, verbose_name='Получатель (收货人)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон (手机号)')),
                ('province', models.CharField(blank=True, max_length=64, verbose_name='Провинция (省)')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='Город (市)')),
                ('district', models.CharField(blank=True, max_length=64, verbose_name='Район (区/县)')),
                ('detail_address', models.CharField(blank=True, max_length=255, verbose_name='Детальный адрес (详细地址)')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='Индекс (邮编)')),
                ('instructions', models.TextField(blank=True, help_text='Напр.: обязательно укажите свой код в имени получателя.', verbose_name='Памятка клиенту')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Адрес доставки (Китай)',
                'verbose_name_plural': 'Адрес доставки (Китай)',
            },
        ),
    ]
