# Generated by Django 6.0.5 on 2026-08-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Имя получателя на складе. Код клиента идёт в конец адреса, перед индексом.', max_length=128, verbose_name='ФИО получателя (收货人)'),
        ),
    ]
