# Generated by Django 6.0.5 on 2026-08-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_deliveryaddress_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'Регистрация клиента'), ('user_login', 'Вход клиента'), ('user_logout', 'Выход клиента'), ('user_blocked', 'Блокировка клиента'), ('user_unblocked', 'Разблокировка клиента'), ('parcel_imported', 'Импорт посылки'), ('parcel_scanned', 'Сканирование посылки'), ('parcel_status_changed', 'Смена статуса посылки'), ('parcel_issued', 'Выдача посылки'), ('city_delivery_created', 'Создана доставка по городу'), ('city_delivery_delivered', 'Завершена доставка по городу'), ('pinduoduo_connected', 'Подключение Pinduoduo'), ('pinduoduo_disconnected', 'Отключение Pinduoduo'), ('pinduoduo_synced', 'Синхронизация Pinduoduo'), ('pinduoduo_session_expired', 'Сессия Pinduoduo истекла'), ('taobao_connected', 'Подключение Taobao'), ('taobao_disconnected', 'Отключение Taobao'), ('taobao_synced', 'Синхронизация Taobao'), ('taobao_session_expired', 'Сессия Taobao истекла'), ('admin_action', 'Действие администратора')], max_length=64, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Индекс (邮编), не используется'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Запасное имя получателя. Основное задаётся у каждого карго отдельно — у них разные люди на приёмке в Китае.', max_length=128, verbose_name='ФИО получателя по умолчанию (收货人)'),
        ),
    ]
