# Generated by Django 6.0.5 on 2026-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_marketplace_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'Регистрация клиента'), ('user_login', 'Вход клиента'), ('user_logout', 'Выход клиента'), ('user_blocked', 'Блокировка клиента'), ('user_unblocked', 'Разблокировка клиента'), ('parcel_imported', 'Импорт посылки'), ('parcel_scanned', 'Сканирование посылки'), ('parcel_status_changed', 'Смена статуса посылки'), ('parcel_issued', 'Выдача посылки'), ('city_delivery_created', 'Создана доставка по городу'), ('city_delivery_delivered', 'Завершена доставка по городу'), ('pinduoduo_connected', 'Подключение Pinduoduo'), ('pinduoduo_disconnected', 'Отключение Pinduoduo'), ('pinduoduo_synced', 'Синхронизация Pinduoduo'), ('pinduoduo_session_expired', 'Сессия Pinduoduo истекла'), ('taobao_connected', 'Подключение Taobao'), ('taobao_disconnected', 'Отключение Taobao'), ('taobao_synced', 'Синхронизация Taobao'), ('taobao_session_expired', 'Сессия Taobao истекла'), ('shop1688_connected', 'Подключение 1688'), ('shop1688_disconnected', 'Отключение 1688'), ('shop1688_synced', 'Синхронизация 1688'), ('shop1688_session_expired', 'Сессия 1688 истекла'), ('admin_action', 'Действие администратора')], max_length=64, verbose_name='Действие'),
        ),
    ]
