# Generated by Django 6.0.5 on 2026-05-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_order_created_at_and_more'),
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.AlterModelOptions(
            name='parcelstatushistory',
            options={'ordering': ('-created_at',), 'verbose_name': 'История статуса посылки', 'verbose_name_plural': 'История статусов посылок'},
        ),
        migrations.AlterField(
            model_name='parcel',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='client_code',
            field=models.CharField(db_index=True, max_length=16, verbose_name='Клиентский код'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('created', 'Оформлен'), ('purchased', 'Выкуплен'), ('waiting_china_warehouse', 'Ожидается на складе в Китае'), ('arrived_china_warehouse', 'Прибыл на склад в Китае'), ('sent_to_kyrgyzstan', 'Отправлен в Кыргызстан'), ('arrived_kyrgyzstan', 'Прибыл в Кыргызстан'), ('at_pickup_point', 'В ПВЗ'), ('city_delivery', 'Передан на доставку по городу'), ('delivered', 'Доставлен'), ('issued', 'Выдан клиенту'), ('cancelled', 'Отменён')], default='created', max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='track_number',
            field=models.CharField(max_length=128, unique=True, verbose_name='Трек-номер'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Объём, м³'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parcels.parcel', verbose_name='Посылка'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='status',
            field=models.CharField(choices=[('created', 'Оформлен'), ('purchased', 'Выкуплен'), ('waiting_china_warehouse', 'Ожидается на складе в Китае'), ('arrived_china_warehouse', 'Прибыл на склад в Китае'), ('sent_to_kyrgyzstan', 'Отправлен в Кыргызстан'), ('arrived_kyrgyzstan', 'Прибыл в Кыргызстан'), ('at_pickup_point', 'В ПВЗ'), ('city_delivery', 'Передан на доставку по городу'), ('delivered', 'Доставлен'), ('issued', 'Выдан клиенту'), ('cancelled', 'Отменён')], max_length=64, verbose_name='Статус'),
        ),
    ]
