# Generated by Django 6.0.5 on 2026-07-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargocompany_price_per_kg_usd'),
        ('parcels', '0003_parcel_cargo_alter_parcel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='cargo',
            field=models.ForeignKey(blank=True, help_text='Может быть пустым для «ничьих» посылок со склада в Китае до привязки к клиенту.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='cargo.cargocompany', verbose_name='Карго-центр'),
        ),
    ]
