# Generated by Django 6.0.5 on 2026-07-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_alter_parcel_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('created', 'Оформлен'), ('purchased', 'Выкуплен'), ('waiting_china_warehouse', 'Ожидается на складе в Китае'), ('arrived_china_warehouse', 'Прибыл на склад в Китае'), ('in_storage', 'Отправлен на хранение'), ('sent_to_kyrgyzstan', 'Отправлен со склада, в пути'), ('in_transit', 'В пути'), ('arrived_kyrgyzstan', 'Прибыл в Кыргызстан'), ('processing', 'Классификация и обработка'), ('at_pickup_point', 'Прибыл в пункт выдачи'), ('city_delivery', 'Передан на доставку по городу'), ('delivered', 'Доставлен'), ('issued', 'Выдан клиенту'), ('cancelled', 'Отменён')], default='created', max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='status',
            field=models.CharField(choices=[('created', 'Оформлен'), ('purchased', 'Выкуплен'), ('waiting_china_warehouse', 'Ожидается на складе в Китае'), ('arrived_china_warehouse', 'Прибыл на склад в Китае'), ('in_storage', 'Отправлен на хранение'), ('sent_to_kyrgyzstan', 'Отправлен со склада, в пути'), ('in_transit', 'В пути'), ('arrived_kyrgyzstan', 'Прибыл в Кыргызстан'), ('processing', 'Классификация и обработка'), ('at_pickup_point', 'Прибыл в пункт выдачи'), ('city_delivery', 'Передан на доставку по городу'), ('delivered', 'Доставлен'), ('issued', 'Выдан клиенту'), ('cancelled', 'Отменён')], max_length=64, verbose_name='Статус'),
        ),
    ]
