# Generated by Django 6.0.5 on 2026-07-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_parcel_is_archived_alter_parcel_status_and_more'),
        ('pickup_points', '0004_alter_pickuppoint_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='pickup_point',
            field=models.ForeignKey(blank=True, help_text='Физический пункт выдачи, где посылка принята (ставится при статусе «В ПВЗ»).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='pickup_points.pickuppoint', verbose_name='ПВЗ приёмки'),
        ),
    ]
