# Generated by Django 6.0.5 on 2026-09-07 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_alter_parcel_status_alter_parcelstatushistory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcelstatushistory',
            index=models.Index(fields=['status', '-created_at'], name='psh_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelstatushistory',
            index=models.Index(fields=['changed_by', '-created_at'], name='psh_actor_created_idx'),
        ),
    ]
