# Generated by Django 6.0.5 on 2026-09-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_parcelstatushistory_psh_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='client_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Итоговая сумма к оплате. Отличается от расчёта по тарифу, когда были обрешётка, упаковка или своя договорённость.', max_digits=12, null=True, verbose_name='Цена клиенту'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='crating',
            field=models.BooleanField(default=False, verbose_name='Обрешётка'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Заполняется при доставке по городу.', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Высота, см'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Длина, см'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='Когда клиенту ушло последнее уведомление о статусе.', null=True, verbose_name='Уведомление отправлено'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='packaging',
            field=models.BooleanField(default=False, verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично оплачен'), ('paid', 'Оплачен')], db_index=True, default='unpaid', max_length=16, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receipt_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз из ПВЗ'), ('city_delivery', 'Доставка по городу')], default='pickup', max_length=16, verbose_name='Способ получения'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='usd_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Курс на момент расчёта: потом он меняется, а счёт клиента — нет.', max_digits=10, null=True, verbose_name='Курс USD'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Ширина, см'),
        ),
    ]
