# Generated by Django 6.0.5 on 2026-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_parcel_client_price_parcel_crating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('created', 'Оформлен'), ('purchased', 'Выкуплен'), ('waiting_china_warehouse', 'Ожидается на складе в Китае'), ('arrived_china_warehouse', 'Прибыл на склад в Китае'), ('in_storage', 'Отправлен на хранение'), ('sent_to_kyrgyzstan', 'Отправлен со склада, в пути'), ('in_transit', 'В пути'), ('arrived_kyrgyzstan', 'Прибыл в Кыргызстан'), ('processing', 'Классификация и обработка'), ('arrived_topa', 'Прибыл в Топа'), ('customs', 'На таможне'), ('at_pickup_point', 'Прибыл в пункт выдачи'), ('city_delivery', 'Передан на доставку по городу'), ('delivered', 'Доставлен'), ('issued', 'Выдан клиенту'), ('cancelled', 'Отменён')], default='created', max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='status',
            field=models.CharField(choices=[('created', 'Оформлен'), ('purchased', 'Выкуплен'), ('waiting_china_warehouse', 'Ожидается на складе в Китае'), ('arrived_china_warehouse', 'Прибыл на склад в Китае'), ('in_storage', 'Отправлен на хранение'), ('sent_to_kyrgyzstan', 'Отправлен со склада, в пути'), ('in_transit', 'В пути'), ('arrived_kyrgyzstan', 'Прибыл в Кыргызстан'), ('processing', 'Классификация и обработка'), ('arrived_topa', 'Прибыл в Топа'), ('customs', 'На таможне'), ('at_pickup_point', 'Прибыл в пункт выдачи'), ('city_delivery', 'Передан на доставку по городу'), ('delivered', 'Доставлен'), ('issued', 'Выдан клиенту'), ('cancelled', 'Отменён')], max_length=64, verbose_name='Статус'),
        ),
    ]
