# Generated by Django 6.0.5 on 2026-09-24 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_cargocompany_is_listed'),
        ('parcels', '0010_alter_parcel_status_alter_parcelstatushistory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(max_length=32, verbose_name='Проставленный статус')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Строк в файле')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки по строкам')),
                ('detected', models.JSONField(blank=True, default=dict, verbose_name='Распознанная раскладка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_imports', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcel_imports', to='cargo.cargocompany', verbose_name='Карго-центр')),
            ],
            options={
                'verbose_name': 'Импорт накладной',
                'verbose_name_plural': 'Импорты накладных',
                'ordering': ('-created_at',),
            },
        ),
    ]
