# Generated by Django 6.0.5 on 2026-09-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0011_parcelimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelstatushistory',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='parcels.parcelimport', verbose_name='Импорт накладной'),
        ),
    ]
