# Generated by Django 6.0.5 on 2026-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('sort_order', 'title'), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='client_code_strategy',
            field=models.CharField(choices=[('query_param', 'Подставить в URL'), ('clipboard', 'Скопировать в буфер обмена'), ('manual_instruction', 'Показать инструкцию')], default='query_param', max_length=32, verbose_name='Стратегия передачи клиентского кода'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='shop_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_type',
            field=models.CharField(choices=[('webview', 'WebView в приложении'), ('external_app', 'Внешнее приложение'), ('browser', 'Внешний браузер')], default='webview', max_length=32, verbose_name='Способ открытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='query_param_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Параметр в URL'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
