# Generated by Django 6.0.5 on 2026-05-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinduoduoaccount',
            options={'ordering': ('-created_at',), 'verbose_name': 'Аккаунт Pinduoduo', 'verbose_name_plural': 'Аккаунты Pinduoduo'},
        ),
        migrations.AddField(
            model_name='pinduoduoaccount',
            name='last_sync_error',
            field=models.TextField(blank=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='pinduoduoaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='pinduoduoaccount',
            name='external_user_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID на стороне Pinduoduo'),
        ),
        migrations.AlterField(
            model_name='pinduoduoaccount',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='Подключён'),
        ),
        migrations.AlterField(
            model_name='pinduoduoaccount',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AlterField(
            model_name='pinduoduoaccount',
            name='session_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные сессии'),
        ),
        migrations.AlterField(
            model_name='pinduoduoaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='pinduoduoaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinduoduo_account', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
