# Generated by Django 6.0.5 on 2026-08-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_pinduoduoaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinduoduoaccount',
            name='last_expire_reason',
            field=models.CharField(blank=True, help_text='Что сообщило приложение: login_redirect, no_cookies, banned…', max_length=64, verbose_name='Причина последнего разлогина'),
        ),
        migrations.AddField(
            model_name='pinduoduoaccount',
            name='session_expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сессия истекла'),
        ),
        migrations.AddField(
            model_name='pinduoduoaccount',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сессия начата'),
        ),
    ]
