# Generated by Django 6.0.5 on 2026-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_marketplace_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace',
            field=models.CharField(choices=[('pinduoduo', 'Pinduoduo'), ('taobao', 'Taobao'), ('1688', '1688')], db_index=True, default='pinduoduo', max_length=32, verbose_name='Маркетплейс'),
        ),
    ]
