# Generated by Django 6.0.5 on 2026-05-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_delivery', '0001_initial'),
        ('parcels', '0002_alter_parcel_options_and_more'),
        ('pickup_points', '0002_alter_pickuppoint_options_alter_pickuppoint_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydeliveryrequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заявка на доставку по городу', 'verbose_name_plural': 'Заявки на доставку по городу'},
        ),
        migrations.AddField(
            model_name='citydeliveryrequest',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_city_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AddField(
            model_name='citydeliveryrequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлено'),
        ),
        migrations.AddField(
            model_name='citydeliveryrequest',
            name='delivery_time_slot',
            field=models.CharField(blank=True, max_length=64, verbose_name='Желаемое время'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='address',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_delivery_requests', to='parcels.parcel', verbose_name='Посылка'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='recipient_name',
            field=models.CharField(max_length=255, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='recipient_phone',
            field=models.CharField(max_length=32, verbose_name='Телефон получателя'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('price_calculated', 'Стоимость рассчитана'), ('accepted', 'Принята'), ('assigned_to_courier', 'Назначен курьер'), ('in_delivery', 'В доставке'), ('delivered', 'Доставлена'), ('cancelled', 'Отменена')], default='created', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_delivery_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='CityDeliveryTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовая стоимость')),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за кг')),
                ('free_weight_kg', models.DecimalField(decimal_places=3, default=0, help_text='Вес, до которого взимается только базовая стоимость', max_digits=10, verbose_name='Бесплатный вес, кг')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Минимальная стоимость')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('pickup_point', models.ForeignKey(blank=True, help_text='Если задано — тариф применяется только к посылкам этого ПВЗ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_delivery_tariffs', to='pickup_points.pickuppoint', verbose_name='ПВЗ')),
            ],
            options={
                'verbose_name': 'Тариф доставки по городу',
                'verbose_name_plural': 'Тарифы доставки по городу',
                'ordering': ('-is_default', 'title'),
            },
        ),
        migrations.AddField(
            model_name='citydeliveryrequest',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='city_delivery.citydeliverytariff', verbose_name='Тариф'),
        ),
    ]
