# Generated by Django 6.0.5 on 2026-06-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('city_delivery', '0002_alter_citydeliveryrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydeliverytariff',
            name='cargo',
            field=models.ForeignKey(blank=True, help_text='Карго, к которому относится тариф. Для общего тарифа (без ПВЗ) ограничивает выбор этим карго.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_delivery_tariffs', to='cargo.cargocompany', verbose_name='Карго-центр'),
        ),
    ]
