# Generated by Django 6.0.5 on 2026-10-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_cargocompany_is_listed'),
        ('city_delivery', '0003_citydeliverytariff_cargo'),
        ('parcels', '0012_parcelstatushistory_source_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydeliveryrequest',
            name='is_standing',
            field=models.BooleanField(default=False, help_text='Оформлена без посылок: «всё моё везите сюда». Подхватывает посылки, приходящие в ПВЗ, а после доставки открывается заново', verbose_name='Постоянная'),
        ),
        migrations.AddField(
            model_name='citydeliveryrequest',
            name='parcels',
            field=models.ManyToManyField(blank=True, related_name='city_deliveries', to='parcels.parcel', verbose_name='Посылки'),
        ),
        migrations.AddField(
            model_name='citydeliveryrequest',
            name='suggested_point',
            field=models.CharField(blank=True, help_text='Просьба, а не готовый адрес: оператор согласует и заводит точку', max_length=255, verbose_name='Предложенная клиентом точка'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='citydeliveryrequest',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_delivery_requests', to='parcels.parcel', verbose_name='Посылка (старое поле)'),
        ),
        migrations.CreateModel(
            name='CityDeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Уточнение адреса')),
                ('work_hours', models.CharField(blank=True, max_length=64, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивная точка не показывается клиенту, но остаётся в истории заявок', verbose_name='Активна')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_delivery_points', to='cargo.cargocompany', verbose_name='Карго-центр')),
            ],
            options={
                'verbose_name': 'Точка доставки по городу',
                'verbose_name_plural': 'Точки доставки по городу',
                'ordering': ('position', 'title'),
            },
        ),
        migrations.AddField(
            model_name='citydeliveryrequest',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='city_delivery.citydeliverypoint', verbose_name='Точка выдачи'),
        ),
    ]
