# Generated by Django 6.0.5 on 2026-05-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Номер заказа у поставщика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('pinduoduo', 'Pinduoduo'), ('taobao', 'Taobao'), ('1688', '1688'), ('manual', 'Вручную')], default='manual', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Оформлен'), ('paid', 'Оплачен'), ('purchased', 'Выкуплен'), ('waiting_china_warehouse', 'Ожидается на складе в Китае'), ('arrived_china_warehouse', 'Прибыл на склад в Китае'), ('cancelled', 'Отменён')], default='created', max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Трек-номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
