# Generated by Django 6.0.5 on 2026-06-10 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_order_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('external_order_id', ''), _negated=True), fields=('user', 'source', 'external_order_id'), name='unique_order_per_source_external_id'),
        ),
    ]
