# Generated by Django 6.0.5 on 2026-06-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_devicetoken_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('auth', 'Авторизация'), ('order_created', 'Новый заказ'), ('order_status_changed', 'Изменение статуса заказа'), ('parcel_status_changed', 'Изменение статуса посылки'), ('parcel_at_pickup_point', 'Посылка в ПВЗ'), ('city_delivery_created', 'Создана доставка по городу'), ('city_delivery_status_changed', 'Изменение статуса доставки'), ('pinduoduo_connected', 'Pinduoduo подключён'), ('pinduoduo_synced', 'Pinduoduo синхронизирован'), ('marketing', 'Рекламное'), ('system', 'Системное')], default='system', max_length=64, verbose_name='Тип'),
        ),
    ]
