# Generated by Django 6.0.5 on 2026-09-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, help_text='Показывается в карточке уведомления у клиента.', null=True, upload_to='notifications/', verbose_name='Картинка'),
        ),
    ]
