# Generated by Django 6.0.5 on 2026-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('auth', 'Авторизация'), ('order_created', 'Новый заказ'), ('order_status_changed', 'Изменение статуса заказа'), ('parcel_status_changed', 'Изменение статуса посылки'), ('parcel_at_pickup_point', 'Посылка в ПВЗ'), ('city_delivery_created', 'Создана доставка по городу'), ('city_delivery_status_changed', 'Изменение статуса доставки'), ('pinduoduo_connected', 'Pinduoduo подключён'), ('pinduoduo_synced', 'Pinduoduo синхронизирован'), ('taobao_connected', 'Taobao подключён'), ('taobao_synced', 'Taobao синхронизирован'), ('shop1688_connected', '1688 подключён'), ('shop1688_synced', '1688 синхронизирован'), ('marketing', 'Рекламное'), ('system', 'Системное'), ('personal', 'Личное сообщение')], default='system', max_length=64, verbose_name='Тип'),
        ),
    ]
