# Generated by Django 6.0.5 on 2026-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocompany',
            name='price_per_kg_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стоимость доставки за 1 кг в долларах США', max_digits=8, verbose_name='Цена за кг, $'),
        ),
    ]
