# Generated by Django 6.0.5 on 2026-08-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargocompany_price_per_kg_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocompany',
            name='code',
            field=models.CharField(blank=True, help_text='Код склада в Китае (напр. x69610). Клиенты этого карго указывают его в адресе доставки перед своим кодом.', max_length=32, null=True, unique=True, verbose_name='Код карго'),
        ),
    ]
