# Generated by Django 6.0.5 on 2026-08-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargocompany_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocompany',
            name='client_code_prefix',
            field=models.CharField(default='C', help_text='Буквы перед номером клиента: «X» → X0001, X0002… Менять можно в любой момент — уже выданные коды не пересчитываются.', max_length=6, verbose_name='Префикс кода клиента'),
        ),
        migrations.AddField(
            model_name='cargocompany',
            name='client_code_seq',
            field=models.PositiveIntegerField(default=0, help_text='Номер последнего выданного клиентского кода этого карго.', verbose_name='Счётчик кодов клиентов'),
        ),
    ]
