# Generated by Django 6.0.5 on 2026-08-05 20:36

from django.db import migrations, models


def dedupe_prefixes(apps, schema_editor):
    """Развести одинаковые префиксы перед включением unique.

    До этой миграции у всех карго префикс «C». Самое старое карго его
    сохраняет, остальным даём «C2», «C3»… — владельцы потом выберут свой
    в настройках карго.
    """
    CargoCompany = apps.get_model("cargo", "CargoCompany")
    seen = set()
    for cargo in CargoCompany.objects.order_by("id"):
        prefix = (cargo.client_code_prefix or "C").strip() or "C"
        if prefix.casefold() not in seen:
            seen.add(prefix.casefold())
            if prefix != cargo.client_code_prefix:
                cargo.client_code_prefix = prefix
                cargo.save(update_fields=["client_code_prefix"])
            continue
        n = 2
        while f"{prefix}{n}".casefold() in seen or len(f"{prefix}{n}") > 6:
            n += 1
            if len(f"{prefix}{n}") > 6:  # префикс уже длинный — режем хвост
                prefix = prefix[:-1] or "C"
                n = 2
        cargo.client_code_prefix = f"{prefix}{n}"
        seen.add(cargo.client_code_prefix.casefold())
        cargo.save(update_fields=["client_code_prefix"])


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_cargocompany_client_code_prefix_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_prefixes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cargocompany',
            name='client_code_prefix',
            field=models.CharField(default='C', help_text='Буквы перед номером клиента: «X» → X0001, X0002… Уникален на карго: по коду клиента коробку опознают в Китае, где посылки всех карго лежат вместе. Менять можно в любой момент — уже выданные коды не пересчитываются.', max_length=6, unique=True, verbose_name='Префикс кода клиента'),
        ),
    ]
