# Generated by Django 6.0.5 on 2026-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_rename_price_to_kgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocompany',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Имя, которое клиенты этого карго ставят получателем в заказе на маркетплейсе. У каждого карго свой человек на приёмке.', max_length=128, verbose_name='ФИО получателя в Китае (收货人)'),
        ),
    ]
