# Generated by Django 6.0.5 on 2026-08-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_cargo_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargocompany',
            name='client_code_prefix',
            field=models.CharField(default='C', help_text='Символы перед номером клиента: «X» → X0001, «КК-» → КК-0001, «仓» → 仓0001. До 10 символов, любые кроме пробелов. Уникален на карго: по коду клиента коробку опознают в Китае, где посылки всех карго лежат вместе. Менять можно в любой момент — уже выданные коды не пересчитываются.', max_length=10, unique=True, verbose_name='Префикс кода клиента'),
        ),
    ]
