# Generated by Django 6.0.5 on 2026-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_widen_client_code_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocompany',
            name='address_suffix',
            field=models.CharField(blank=True, help_text='Символы в конец детального адреса — у каждого карго свои: «…仓315库» + «东» → «…仓315库东». Пишется слитно, без пробела.', max_length=16, verbose_name='Приписка к адресу склада'),
        ),
    ]
