# Generated by Django 6.0.5 on 2026-09-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_cargo_address_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocompany',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='Снимите, чтобы карго не появлялось в выборе при регистрации. Вход и работа продолжают действовать — так живёт тестовое карго.', verbose_name='Показывать клиентам'),
        ),
    ]
